In [3]:
import pandas as pd
import json
from math import log, isnan

In [4]:
data = pd.read_excel("./Bloomberg_Supply_Chain.xlsx", sheet_name=None)
main_data = data["SPLC_L2"]
main_data1 = data["SPLC_L1"]
company_info = data["Company Info"]

In [5]:
pd.set_option('display.max_columns', 30)
main_data,head()

,Central Ticker,Central Company,Central Country,Stock Number,Listed Country,Supplier Registered Name,Supplier Company,Supplier Ticker,Supplier Country,Supplier Market Cap,Latest Inv. Growth,% Revenue get from central,Relationship Value,Currency,Account As Type,%Cost,Relationship Value USD,Source,As Of Date
0,000710 CH Equity,Berry Genomics Co Ltd,CN,BNGO,US,BIONANO GENOMICS INC,BioNano Genomics Inc,BNGO US Equity,US,305.07M,0.1999,0.06,1.30M,CNY,COGS,0.0090,195000.0,*2018Q2 CF,2018-08-17
1,000710 CH Equity,Berry Genomics Co Ltd,CN,732,HK,TRULY INTERNATIONAL HOLDINGS,Truly International Holdings Ltd,732 HK Equity,HK,3.67B,-0.0001,NaN,NaN,NaN,NaN,NaN,0.0,2016A CF,2017-02-27
2,1506 TT Equity,Right WAY Industrial Co Ltd,TW,NaN,--,--,Kainan Metals Industries Co Ltd,ABDBKZ TT Equity,--,--,--,NaN,14.50M,TWD,COGS,0.0507,464000.0,2017A CF,2018-06-06
3,1506 TT Equity,Right WAY Industrial Co Ltd,TW,NaN,--,--,Chung Ming Enterprise Co Ltd,Chung Min... Equity,--,--,--,NaN,9.45M,TWD,COGS,0.0331,302400.0,2017A CF,2018-06-06
4,000559 CH Equity,Wanxiang Qianchao Co Ltd,CN,NaN,--,--,Jiangyin Taifu Xingcheng Special Material Co Ltd,0165637D CH Equity,--,--,--,NaN,115.09M,CNY,COGS,0.0520,17263500.0,2017A CF,2018-03-29

In [37]:
company_info.head()

,Ticker,Company Name,GICS SubInd Name,GICS Ind Name,GICS Sector,Market Cap,Listed Location,FX rate,Market Cap USD,Price:D-1,P/E,Total Return YTD,Revenue T12M,EPS T12M
0,422 HK Equity,Vietnam Manufacturing & Export Processing Hold...,Motorcycle Manufacturers,Automobiles,Consumer Discretionary,2.496120e+08,HK,0.128205,3.200154e+07,0.275000,NaN,-6.779655,9.154676e+07,-0.046098
1,729 HK Equity,FDG Electric Vehicles Ltd,Automobile Manufacturers,Automobiles,Consumer Discretionary,1.448123e+09,HK,0.128205,1.856568e+08,0.053000,NaN,8.163267,1.030148e+09,-0.102917
2,1114 HK Equity,Brilliance China Automotive Holdings Ltd,Automobile Manufacturers,Automobiles,Consumer Discretionary,4.359113e+10,HK,0.128205,5.588606e+09,8.640000,6.341441,48.198979,4.377263e+09,1.153740
3,423 HK Equity,Hong Kong Economic Times Holdings Ltd,Publishing,Media,Communication Services,7.337200e+08,HK,0.128205,9.406667e+07,1.700000,9.468747,25.000002,1.258609e+09,0.179538
4,425 HK Equity,Minth Group Ltd,Auto Parts & Equipment,Auto Components,Consumer Discretionary,3.120350e+10,HK,0.128205,4.000449e+09,27.200001,15.774044,7.722775,1.255320e+10,1.451144

In [6]:
company_cap = {}
for _, info in company_info.iterrows():
    if (info["Ticker"] not in company_cap) or company_cap[info["Ticker"]] == 0:
        company_cap[info["Ticker"]] = int(info["Market Cap USD"])

In [7]:
def newnode(name, type, country, market_cap):
    if pd.isna(country): country = "--"
    
    node = {}
    if market_cap is None:
        node["size"] = 5
        node["market_cap"] = "--"
    else:
        node["size"] = max(log(market_cap) - 12, 5)
        node["market_cap"] = "USD {:,}".format(market_cap)
    node["name"] = name
    node["type"] = type
    node["score"] = 1.0
    node["country"] = country
    return node

nodes = []
company_id = {}
'''
for _, info in main_data1.iterrows():
    
    central = info["Central Company"]
    central_stock = info["Central Ticker"]
    central_country = info["Central Country"]
    
    if central_stock not in company_cap:
        company_cap[central_stock] = None
    
    if central_stock not in company_id:
        nodes.append(newnode(central, "central", central_country, company_cap[central_stock]))
        company_id[central_stock] = len(company_id)
        
        
for _, info in main_data1.iterrows():
    supplier = info["Supplier Company"]
    supplier_stock = info["Supplier Ticker"]
    supplier_country = info["Supplier Country"]
    
    if supplier_stock not in company_cap:
        company_cap[supplier_stock] = None
    
    if supplier_stock not in company_id:
        nodes.append(newnode(supplier, "supplier", supplier_country, company_cap[supplier_stock]))
        company_id[supplier_stock] = len(company_id)
'''

for _, info in main_data.iterrows():
    
    central = info["Central Company"]
    central_stock = info["Central Ticker"]
    central_country = info["Central Country"]
    
    if central_stock not in company_cap:
        company_cap[central_stock] = None
    
    if central_stock not in company_id:
        nodes.append(newnode(central, "central", central_country, company_cap[central_stock]))
        company_id[central_stock] = len(company_id)
        
        
for _, info in main_data.iterrows():
    supplier = info["Supplier Company"]
    supplier_stock = info["Supplier Ticker"]
    supplier_country = info["Supplier Country"]
    
    if supplier_stock not in company_cap:
        company_cap[supplier_stock] = None
    
    if supplier_stock not in company_id:
        nodes.append(newnode(supplier, "supplier", supplier_country, company_cap[supplier_stock]))
        company_id[supplier_stock] = len(company_id)

nodes[:5]

[{'country': 'CN',
  'market_cap': 'USD 2,124,975,667',
  'name': 'Berry Genomics Co Ltd',
  'score': 1.0,
  'size': 9.477026188433701,
  'type': 'central'},
 {'country': 'TW',
  'market_cap': '--',
  'name': 'Right WAY Industrial Co Ltd',
  'score': 1.0,
  'size': 5,
  'type': 'central'},
 {'country': 'CN',
  'market_cap': 'USD 2,833,001,164',
  'name': 'Wanxiang Qianchao Co Ltd',
  'score': 1.0,
  'size': 9.764602468666574,
  'type': 'central'},
 {'country': 'TW',
  'market_cap': '--',
  'name': 'JUI LI Enterprise Co Ltd',
  'score': 1.0,
  'size': 5,
  'type': 'central'},
 {'country': 'SE',
  'market_cap': 'USD 7,285,579,776',
  'name': 'Autoliv Inc',
  'score': 1.0,
  'size': 10.70916285832735,
  'type': 'central'}]

In [8]:
len(nodes)

1932

In [9]:
links = []

'''
for _, info in main_data1.iterrows():
    central = info["Central Company"]
    central_stock = info["Central Ticker"]
    supplier = info["Supplier Company"]
    supplier_stock = info["Supplier Ticker"]
    relation_value = info["Relationship Value USD"]
    
    if isinstance(relation_value, float) or isinstance(relation_value, int):
        if isnan(relation_value): relation_value = 1
   
    link = {}
    link["source"] = company_id[supplier_stock]
    link["target"] = company_id[central_stock]
    link["score"] = max(log(relation_value + 1) / 5 - 1, 1)
    
    links.append(link)
'''

for _, info in main_data.iterrows():
    central = info["Central Company"]
    central_stock = info["Central Ticker"]
    supplier = info["Supplier Company"]
    supplier_stock = info["Supplier Ticker"]
    relation_value = info["Relationship Value USD"]
    
    if isinstance(relation_value, float) or isinstance(relation_value, int):
        if isnan(relation_value): relation_value = 1
    '''
    # convert relationship value to number
    if isinstance(relation_value, float) or isinstance(relation_value, int):
        if isnan(relation_value): rv = 1
        else: rv = relation_value
    else:
        base = 1
        if relation_value[-1] == 'k':
            base = 1e3
        elif relation_value[-1] == 'M':
            base = 1e6
        elif relation_value[-1] == 'B':
            base = 1e9
        elif relation_value[-1] == 'T':
            base = 1e12

        if base > 1:
            rv = float(relation_value[:-1]) * base
        else:
            rv = float(relation_value)
    '''
    link = {}
    link["source"] = company_id[supplier_stock]
    link["target"] = company_id[central_stock]
    link["score"] = max(log(relation_value + 1) / 5 - 1, 1)
    
    links.append(link)

links[:5]

[{'score': 1.4361519931475728, 'source': 141, 'target': 0},
 {'score': 1, 'source': 142, 'target': 0},
 {'score': 1.6095283972756969, 'source': 143, 'target': 1},
 {'score': 1.5239018460320706, 'source': 144, 'target': 1},
 {'score': 2.332821012396894, 'source': 145, 'target': 2}]

In [10]:
len(links)

3993

In [11]:
json.dump({"nodes": nodes, "links": links}, open("automobile_sos.json", "w"), indent=2)

In [74]:
# supplier countries
countries = set()
for n in nodes:
    if n["type"] == "supplier":
        countries.add(n["country"])
countries = sorted(countries)
for c in countries:
    print("<option value=\"{}\">{}</option>".format(c, c))

<option value="--">--</option>
<option value="AT">AT</option>
<option value="BE">BE</option>
<option value="BR">BR</option>
<option value="CA">CA</option>
<option value="CH">CH</option>
<option value="CN">CN</option>
<option value="DE">DE</option>
<option value="ES">ES</option>
<option value="FR">FR</option>
<option value="GB">GB</option>
<option value="HK">HK</option>
<option value="IE">IE</option>
<option value="IL">IL</option>
<option value="IN">IN</option>
<option value="IT">IT</option>
<option value="JP">JP</option>
<option value="KR">KR</option>
<option value="LU">LU</option>
<option value="MX">MX</option>
<option value="NL">NL</option>
<option value="NO">NO</option>
<option value="SA">SA</option>
<option value="SE">SE</option>
<option value="SG">SG</option>
<option value="TH">TH</option>
<option value="TR">TR</option>
<option value="TW">TW</option>
<option value="US">US</option>
<option value="ZA">ZA</option>

In [20]:
data = json.load(open("automobile_sos.json", "r"))
print(len(data["nodes"]), len(data["links"]))

1932 3993